{-# LANGUAGE OverloadedStrings #-}
-- | Haskell test suite: descriptor handling, layer plan and placement.
-- Pure logic only -- no GPU, no weights.
module Main (main) where

import Control.Monad (unless)
import Data.Aeson (Value(..), eitherDecodeStrict', encode)
import qualified Data.Aeson.Key as Key
import qualified Data.Aeson.KeyMap as KM
import Data.List (isInfixOf, nub)
import Data.Maybe (fromMaybe)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Lazy as BL
import System.Environment (lookupEnv)
import System.IO (hPutStrLn, stderr)
import Test.Hspec

import Infer.Config
import Infer.Descriptor
import Infer.Descriptor.Adapter.Qwen35
import Infer.Model
import Infer.Placement hiding (layerDevice)

-- | The frozen Qwen3.8-27B descriptor, as generated by the family adapter.
-- Mirrors descriptors/qwen38-27b.json so schema or adapter drift fails here
-- instead of after a ten-minute weight load.
qwen38 :: Descriptor
qwen38 = Descriptor
  { dVersion = descVersion
  , dFamily = "qwen3_5"
  , dModelType = "qwen3_5_text"
  , dNumLayers = 64
  , dHiddenSize = 5120
  , dIntermediateSize = 17408
  , dVocabSize = 248320
  , dRmsEps = 1e-6
  , dMaxPositionEmbeddings = 262144
  , dMaxSeqLen = 4096
  , dNumHeads = 24
  , dNumKvHeads = 4
  , dHeadDim = 256
  , dRotaryDim = 64
  , dRotaryTheta = 1e7
  , dNormStyle = "gemma"
  , dAttnQkNorm = True
  , dAttnOutputGate = True
  , dQGateInterleave = True
  , dGdnConvDim = 10240
  , dGdnValueDim = 6144
  , dGdnNumVHeads = 48
  , dGdnNumKHeads = 16
  , dGdnHeadDim = 128
  , dGdnConvKernel = 4
  , dFlaChunkSize = 64
  , dMaxChunk = 128
  , dTpSize = 1
  , dTpRank = 0
  , dEpSize = 1
  , dEpRank = 0
  , dMoeNumExperts = 0
  , dMoeTopK = 0
  , dMoeIntermediateSize = 0
  , dMoeRouterScoring = "softmax"
  , dMoeNormTopkProb = False
  , dMoeNumSharedExperts = 0
  , dMoeSharedIntermediateSize = 0
  , dMoeRoutedScalingFactor = 1.0
  , dMoeSharedGateScalar = False
  , dEosTokens = [248046, 248044]
  , dLayerMixers =
      [ if (i + 1) `mod` 4 == 0 then MFullAttention else MGatedDeltaNet
      | i <- [0 .. 63] ]
  , dLayerFfns = replicate 64 FDense
  , dRoleTemplates = qwen38Roles
  , dRoleShards = defaultShards qwen38Roles
  }

-- | Qwen3.8-27B weight templates; 'defaultShards' derives the per-role
-- tensor-parallel rules from them (no-ops while tp_size is 1).
qwen38Roles :: [(Role, String)]
qwen38Roles =
      [ (REmbed, "model.language_model.embed_tokens.weight")
      , (RLmHead, "lm_head.weight")
      , (RFinalNorm, "model.language_model.norm.weight")
      , (RAttnQ, "model.language_model.layers.%d.self_attn.q_proj.weight")
      , (RAttnK, "model.language_model.layers.%d.self_attn.k_proj.weight")
      , (RAttnV, "model.language_model.layers.%d.self_attn.v_proj.weight")
      , (RAttnO, "model.language_model.layers.%d.self_attn.o_proj.weight")
      , (RAttnQNorm, "model.language_model.layers.%d.self_attn.q_norm.weight")
      , (RAttnKNorm, "model.language_model.layers.%d.self_attn.k_norm.weight")
      , (RGdnQkv, "model.language_model.layers.%d.linear_attn.in_proj_qkv.weight")
      , (RGdnZ, "model.language_model.layers.%d.linear_attn.in_proj_z.weight")
      , (RGdnA, "model.language_model.layers.%d.linear_attn.in_proj_a.weight")
      , (RGdnB, "model.language_model.layers.%d.linear_attn.in_proj_b.weight")
      , (RGdnConv1d, "model.language_model.layers.%d.linear_attn.conv1d.weight")
      , (RGdnDtBias, "model.language_model.layers.%d.linear_attn.dt_bias")
      , (RGdnALog, "model.language_model.layers.%d.linear_attn.A_log")
      , (RGdnOut, "model.language_model.layers.%d.linear_attn.out_proj.weight")
      , (RGdnNorm, "model.language_model.layers.%d.linear_attn.norm.weight")
      , (RInputNorm, "model.language_model.layers.%d.input_layernorm.weight")
      , (RPostNorm, "model.language_model.layers.%d.post_attention_layernorm.weight")
      , (RMlpGate, "model.language_model.layers.%d.mlp.gate_proj.weight")
      , (RMlpUp, "model.language_model.layers.%d.mlp.up_proj.weight")
      , (RMlpDown, "model.language_model.layers.%d.mlp.down_proj.weight")
      ]

-- | DeepSeek-V2-Lite's MLA numbers (from its config): the latent cache is the
-- reason the MLA kind exists, so pin the derived cache claim here; the adapter's
-- reproduction of the real config is checked by the snapshot test.
deepseekMla :: Descriptor
deepseekMla = qwen38
  { dFamily = "deepseek_v2"
  , dModelType = "deepseek_v2"
  , dLayerMixers = replicate 64 MMlaAttention
  , dLayerFfns = replicate 64 FMoe
  , dIntermediateSize = 10944
  , dNumHeads = 16
  , dNumKvHeads = 16
  , dHeadDim = 192
  , dRotaryDim = 64
  , dRotaryTheta = 1e4
  , dNormStyle = "plain"
  , dAttnQkNorm = False
  , dAttnOutputGate = False
  , dQGateInterleave = False
  , dMlaKvLoraRank = 512
  , dMlaQkNopeHeadDim = 128
  , dMlaQkRopeHeadDim = 64
  , dMlaVHeadDim = 128
  , dMoeNumExperts = 64
  , dMoeTopK = 6
  , dMoeIntermediateSize = 1408
  , dMoeRouterScoring = "softmax"
  , dMoeNormTopkProb = False
  , dMoeNumSharedExperts = 2
  , dMoeSharedIntermediateSize = 1408
  , dRoleTemplates = mlaRoles
  , dRoleShards = defaultShards mlaRoles
  }
  where
    layer suffix = "model.layers.%d." ++ suffix
    mlaRoles =
      [ (REmbed, "model.embed_tokens.weight")
      , (RLmHead, "lm_head.weight")
      , (RFinalNorm, "model.norm.weight")
      , (RInputNorm, layer "input_layernorm.weight")
      , (RPostNorm, layer "post_attention_layernorm.weight")
      , (RMlaQ, layer "self_attn.q_proj.weight")
      , (RMlaKvA, layer "self_attn.kv_a_proj_with_mqa.weight")
      , (RMlaKvANorm, layer "self_attn.kv_a_layernorm.weight")
      , (RMlaKvB, layer "self_attn.kv_b_proj.weight")
      , (RMlaO, layer "self_attn.o_proj.weight")
      , (RMlpGate, layer "mlp.gate_proj.weight")
      , (RMlpUp, layer "mlp.up_proj.weight")
      , (RMlpDown, layer "mlp.down_proj.weight")
      , (RMoeRouter, layer "mlp.gate.weight")
      , (RMoeExpertGate, layer "mlp.experts.%e.gate_proj.weight")
      , (RMoeExpertUp, layer "mlp.experts.%e.up_proj.weight")
      , (RMoeExpertDown, layer "mlp.experts.%e.down_proj.weight")
      , (RMoeSharedGate, layer "mlp.shared_experts.gate_proj.weight")
      , (RMoeSharedUp, layer "mlp.shared_experts.up_proj.weight")
      , (RMoeSharedDown, layer "mlp.shared_experts.down_proj.weight")
      ]

-- | Helper: a validation/placement failure.
isLeftResult :: Either String a -> Bool
isLeftResult (Left _) = True
isLeftResult (Right _) = False

-- | MoE-shaped variant of the fixture: every layer is MoE with 128 experts, and
-- the dense MLP roles are replaced by the routed-expert roles, which
-- 'defaultShards' marks @out_experts@.
qwen38Moe :: Descriptor
qwen38Moe = qwen38
  { dLayerFfns = replicate 64 FMoe
  , dMoeNumExperts = 128
  , dMoeTopK = 8
  , dMoeIntermediateSize = 768
  , dMoeRouterScoring = "softmax"
  , dMoeNormTopkProb = True
  , dRoleTemplates = moeRoles
  , dRoleShards = defaultShards moeRoles
  }
  where
    moeRoles =
      [ (r, t) | (r, t) <- qwen38Roles, r `notElem` [RMlpGate, RMlpUp, RMlpDown] ]
        ++ [ (RMoeRouter, "model.language_model.layers.%d.mlp.gate.weight")
           , (RMoeExpertGate, "model.language_model.layers.%d.mlp.experts.%e.gate_proj.weight")
           , (RMoeExpertUp, "model.language_model.layers.%d.mlp.experts.%e.up_proj.weight")
           , (RMoeExpertDown, "model.language_model.layers.%d.mlp.experts.%e.down_proj.weight")
           ]

-- | Helper: the result is a Left whose message contains the given text.
mentions :: String -> Either String a -> Bool
mentions needle (Left err) = needle `isInfixOf` err
mentions _ (Right _) = False

-- | Remove top-level keys from an encoded descriptor (to exercise the defaults
-- of the optional tensor-parallel keys).
dropDescriptorKeys :: [String] -> BS.ByteString -> BS.ByteString
dropDescriptorKeys keys bytes = case eitherDecodeStrict' bytes of
  Right (Object o) ->
    BL.toStrict (encode (Object (foldr (KM.delete . Key.fromString) o keys)))
  _ -> bytes

-- | Craft an invalid wire document by replacing a literal byte string
-- (replaces every occurrence; the test strings are unique in the document).
replaceBytes :: BS.ByteString -> BS.ByteString -> BS.ByteString -> BS.ByteString
replaceBytes needle replacement = go
  where
    go haystack = case BS.breakSubstring needle haystack of
      (before, rest)
        | BS.null rest -> haystack
        | otherwise ->
            BS.concat [before, replacement, go (BS.drop (BS.length needle) rest)]

-- | Shard rules for the descriptor's role table with a few roles overridden.
shardsFor :: Descriptor -> [(Role, ShardKind)] -> [ShardKind]
shardsFor d overrides =
  [ fromMaybe ShardNone (lookup r overrides) | (r, _) <- dRoleTemplates d ]

main :: IO ()
main = hspec $ do
  describe "Descriptor" $ do
    it "has the Qwen3.8-27B dimensions" $ do
      dNumLayers qwen38 `shouldBe` 64
      dHiddenSize qwen38 `shouldBe` 5120
      dIntermediateSize qwen38 `shouldBe` 17408
      dVocabSize qwen38 `shouldBe` 248320
      dNumHeads qwen38 `shouldBe` 24
      dNumKvHeads qwen38 `shouldBe` 4
      dHeadDim qwen38 `shouldBe` 256
      dRotaryDim qwen38 `shouldBe` 64

    it "derives 16 attention and 48 GDN layers from layer_mixers" $ do
      length (attentionLayers qwen38) `shouldBe` 16
      length (gdnLayers qwen38) `shouldBe` 48

    it "reproduces the historical (index+1) mod 4 == 0 attention layout" $ do
      attentionLayers qwen38 `shouldBe` [i | i <- [0 .. 63], (i + 1) `mod` 4 == 0]

    it "validates and round-trips through the wire format" $ do
      validateDescriptor qwen38 `shouldBe` Right ()
      decodeDescriptor (encodeDescriptor qwen38) `shouldBe` Right qwen38

    it "rejects an unknown descriptor key" $ do
      let broken = "{ \"desc_version\": 1, \"surprise\": 2 }"
      decodeDescriptor broken `shouldSatisfy` mentions "unknown descriptor keys"

    it "rejects a missing descriptor key" $ do
      let broken = "{ \"desc_version\": 1 }"
      decodeDescriptor broken `shouldSatisfy` mentions "is missing"

    it "rejects inconsistent GDN dimensions" $ do
      validateDescriptor qwen38 { dGdnConvDim = 10241 } `shouldSatisfy` isLeftResult

    it "rejects a max_seq_len beyond the position limit" $ do
      validateDescriptor qwen38 { dMaxSeqLen = 262145 } `shouldSatisfy` isLeftResult

    it "reports the KV cache size per token (per layer and aggregated)" $ do
      -- 4 kv heads x 256 dim x 2 (K+V) x 2 bytes = 4096 B per token per layer,
      -- 65536 B per token across the 16 attention layers (the historical number).
      kvBytesPerToken qwen38 `shouldBe` 4096
      kvBytesPerToken qwen38 * length (attentionLayers qwen38) `shouldBe` 65536

    it "defaults tp_size/tp_rank/role_shards when the keys are absent" $ do
      -- A document without the tensor-parallel keys means the historical
      -- single-rank, fully replicated layout.
      let withoutTp = dropDescriptorKeys ["tp_size", "tp_rank", "role_shards"]
                        (encodeDescriptor qwen38)
      decodeDescriptor withoutTp
        `shouldBe` Right qwen38 { dRoleShards = allReplicated qwen38Roles }
      dTpSize qwen38 `shouldBe` 1
      dTpRank qwen38 `shouldBe` 0

    it "derives the default shard rules from the role table" $ do
      let ruleOf role = lookup role (zip (map fst (dRoleTemplates qwen38)) (dRoleShards qwen38))
      ruleOf RAttnQ `shouldBe` Just ShardOutHeads
      ruleOf RAttnK `shouldBe` Just ShardOutHeads
      ruleOf RAttnV `shouldBe` Just ShardOutHeads
      ruleOf RAttnO `shouldBe` Just ShardInDim
      ruleOf RMlpGate `shouldBe` Just ShardOutDim
      ruleOf RMlpUp `shouldBe` Just ShardOutDim
      ruleOf RMlpDown `shouldBe` Just ShardInDim
      -- Replicated roles: norms, embeddings and the GDN mixer stay whole.
      ruleOf REmbed `shouldBe` Just ShardNone
      ruleOf RInputNorm `shouldBe` Just ShardNone
      ruleOf RGdnQkv `shouldBe` Just ShardNone
      ruleOf RGdnOut `shouldBe` Just ShardNone

    it "rejects a shard rule the role cannot carry" $ do
      validateDescriptor qwen38 { dRoleShards = shardsFor qwen38 [(RGdnOut, ShardInDim)] }
        `shouldSatisfy` mentions "role_shards uses a rule"
      validateDescriptor qwen38 { dRoleShards = shardsFor qwen38 [(REmbed, ShardOutDim)] }
        `shouldSatisfy` mentions "role_shards uses a rule"
      validateDescriptor qwen38Moe { dRoleShards = shardsFor qwen38Moe [(RMoeExpertGate, ShardOutDim)] }
        `shouldSatisfy` mentions "role_shards uses a rule"
      validateDescriptor qwen38Moe { dRoleShards = shardsFor qwen38Moe [(RMoeRouter, ShardOutExperts)] }
        `shouldSatisfy` mentions "role_shards uses a rule"

    it "accepts and round-trips a TP2 descriptor with shard rules" $ do
      let tp2 = qwen38 { dTpSize = 2, dTpRank = 1 }
      validateDescriptor tp2 `shouldBe` Right ()
      decodeDescriptor (encodeDescriptor tp2) `shouldBe` Right tp2
      dTpRank tp2 `shouldBe` 1

    it "rejects a tp_rank outside [0, tp_size) and a non-positive tp_size" $ do
      validateDescriptor qwen38 { dTpSize = 2, dTpRank = 2 }
        `shouldSatisfy` mentions "tp_rank"
      validateDescriptor qwen38 { dTpRank = -1 }
        `shouldSatisfy` mentions "tp_rank"
      validateDescriptor qwen38 { dTpSize = 0 }
        `shouldSatisfy` mentions "tp_size"

    it "rejects a role_shards table that is not parallel to the roles" $ do
      validateDescriptor qwen38 { dRoleShards = [] }
        `shouldSatisfy` mentions "role_shards"
      validateDescriptor qwen38 { dRoleShards = init (dRoleShards qwen38) }
        `shouldSatisfy` mentions "role_shards"
      let broken = replaceBytes "\"none\"" "\"none\",\"none\""
                     (encodeDescriptor qwen38)
      decodeDescriptor broken `shouldSatisfy` mentions "role_shards"

    it "rejects an unknown role_shards name on the wire" $ do
      let bogus = replaceBytes "\"none\"" "\"out_heds\"" (encodeDescriptor qwen38)
      decodeDescriptor bogus
        `shouldSatisfy` mentions "unknown role_shards entry"

  describe "Model + Placement" $ do
    it "builds a 64-layer plan for 2 devices with 32 layers each" $ do
      case modelDef qwen38 Pipelined [0, 1] of
        Left err -> expectationFailure err
        Right md -> do
          length (mdLayers md) `shouldBe` 64
          length (filter ((== 0) . layerDevice) (mdLayers md)) `shouldBe` 32
          length (filter ((== 1) . layerDevice) (mdLayers md)) `shouldBe` 32

    it "assigns layers contiguously in order" $ do
      case modelDef qwen38 Pipelined [0, 1] of
        Left err -> expectationFailure err
        Right md -> do
          map layerIndex (mdLayers md) `shouldBe` [0 .. 63]
          all ((== 0) . layerDevice) (take 32 (mdLayers md)) `shouldBe` True
          all ((== 1) . layerDevice) (drop 32 (mdLayers md)) `shouldBe` True

    it "keeps the mixer kinds from the descriptor" $ do
      case modelDef qwen38 Pipelined [0, 1] of
        Left err -> expectationFailure err
        Right md -> attentionLayerIndices md `shouldBe` attentionLayers qwen38

    it "spreads a remainder over the first devices (3 devices, 64 layers)" $ do
      case modelDef qwen38 Pipelined [0, 1, 2] of
        Left err -> expectationFailure err
        Right md -> map length (plLayersPerDevice (mdPlacement md)) `shouldBe` [22, 21, 21]

    it "supports a single device" $ do
      case modelDef qwen38 Pipelined [0] of
        Left err -> expectationFailure err
        Right md -> plLayerDevices (mdPlacement md) `shouldBe` replicate 64 0

    it "rejects duplicate and invalid device lists" $ do
      modelDef qwen38 Pipelined [0, 0] `shouldSatisfy` isLeftResult
      modelDef qwen38 Pipelined [] `shouldSatisfy` isLeftResult
      modelDef qwen38 Pipelined [-1] `shouldSatisfy` isLeftResult

    it "rejects more devices than layers" $ do
      modelDef qwen38 { dNumLayers = 1
                      , dLayerMixers = [MFullAttention]
                      , dLayerFfns = [FDense]
                      } Pipelined [0, 1] `shouldSatisfy` isLeftResult

  describe "Replicated placement (tensor parallel)" $ do
    it "puts every layer on every rank" $ do
      case modelDef qwen38 (Replicated 2 1) [0, 1] of
        Left err -> expectationFailure err
        Right md -> do
          let allLayers = [0 .. 63 :: Int]
          plLayersPerDevice (mdPlacement md) `shouldBe` [allLayers, allLayers]
          length (plLayerDevices (mdPlacement md)) `shouldBe` 64
          plPolicy (mdPlacement md) `shouldBe` Replicated 2 1

    it "supports a four-way split of the Qwen3.8 dimensions" $ do
      -- 24 heads / 4 = 6, 4 kv heads / 4 = 1, 17408 / 4 = 4352.
      case modelDef qwen38 (Replicated 4 1) [0, 1, 2, 3] of
        Left err -> expectationFailure err
        Right md -> length (mdLayers md) `shouldBe` 64

    it "rejects tp that does not divide the sharded dimensions" $ do
      modelDef qwen38 (Replicated 5 1) [0, 1, 2, 3, 4]
        `shouldSatisfy` mentions "does not divide num_heads"
      modelDef qwen38 (Replicated 3 1) [0, 1, 2]
        `shouldSatisfy` mentions "does not divide num_kv_heads"

    it "leaves an all-whole role table alone at any tp" $ do
      case modelDef qwen38 { dRoleShards = allReplicated qwen38Roles } (Replicated 5 1)
             [0, 1, 2, 3, 4] of
        Left err -> expectationFailure err
        Right md -> length (plLayersPerDevice (mdPlacement md)) `shouldBe` 5

    it "rejects a device count that does not match tp * ep" $ do
      modelDef qwen38 (Replicated 2 1) [0] `shouldSatisfy` mentions "devices"
      modelDef qwen38 (Replicated 2 1) [0, 1, 2] `shouldSatisfy` mentions "devices"

    it "rejects MoE layers under tensor parallel" $ do
      modelDef qwen38 { dLayerFfns = replicate 64 FMoe } (Replicated 2 1) [0, 1]
        `shouldSatisfy` mentions "MoE"

  describe "Expert-parallel placement" $ do
    it "splits whole experts across ranks" $ do
      case modelDef qwen38Moe (Replicated 1 2) [0, 1] of
        Left err -> expectationFailure err
        Right md -> do
          plPolicy (mdPlacement md) `shouldBe` Replicated 1 2
          length (plLayersPerDevice (mdPlacement md)) `shouldBe` 2
          plLayersPerDevice (mdPlacement md) `shouldBe` [[0 .. 63], [0 .. 63]]

    it "derives out_experts for the routed-expert roles" $ do
      let ruleOf role =
            lookup role (zip (map fst (dRoleTemplates qwen38Moe)) (dRoleShards qwen38Moe))
      ruleOf RMoeExpertGate `shouldBe` Just ShardOutExperts
      ruleOf RMoeExpertUp `shouldBe` Just ShardOutExperts
      ruleOf RMoeExpertDown `shouldBe` Just ShardOutExperts
      ruleOf RMoeRouter `shouldBe` Just ShardNone

    it "rejects ep that does not divide the expert count" $ do
      modelDef qwen38Moe (Replicated 1 3) [0, 1, 2]
        `shouldSatisfy` mentions "does not divide the expert count"

    it "rejects ep > 1 without MoE layers" $ do
      modelDef qwen38 (Replicated 1 2) [0, 1]
        `shouldSatisfy` mentions "needs at least one MoE layer"

    it "rejects combined tensor and expert parallelism" $ do
      modelDef qwen38Moe (Replicated 2 2) [0, 1, 2, 3]
        `shouldSatisfy` mentions "combined tensor and expert parallelism"

    it "rejects expert roles that are not marked out_experts" $ do
      modelDef qwen38Moe { dRoleShards = allReplicated (dRoleTemplates qwen38Moe) }
        (Replicated 1 2) [0, 1]
        `shouldSatisfy` mentions "out_experts"

  describe "MLA descriptor" $ do
    it "validates and round-trips the DeepSeek-V2-Lite shape" $ do
      validateDescriptor deepseekMla `shouldBe` Right ()
      decodeDescriptor (encodeDescriptor deepseekMla) `shouldBe` Right deepseekMla
      length (mlaLayers deepseekMla) `shouldBe` 64

    it "claims the MLA cache size the kind exists for" $ do
      -- (512 + 64) * 2 bytes = 1152 B per token per layer, against 8 KB for the
      -- equivalent GQA cache (16 heads x 192 dims of K plus V).
      mlaKvBytesPerToken deepseekMla `shouldBe` 1152

    it "requires the MLA dimensions on MLA layers" $ do
      validateDescriptor deepseekMla { dMlaKvLoraRank = 0 }
        `shouldSatisfy` mentions "mla_kv_lora_rank"
      validateDescriptor deepseekMla { dAttnOutputGate = True }
        `shouldSatisfy` mentions "output gate"

  describe "Config" $ do
    it "defaults to two GPUs and a 4096 context" $ do
      rcDevices defaultRuntimeConfig `shouldBe` [0, 1]
      rcMaxSeqLen defaultRuntimeConfig `shouldBe` 4096
      rcDescriptor defaultRuntimeConfig `shouldBe` Nothing

    it "keeps role templates unique per descriptor" $ do
      length (nub (map fst (dRoleTemplates qwen38))) `shouldBe` length (dRoleTemplates qwen38)

  -- Set INFER_MODEL_DIR to a model directory to check that the family adapter
  -- still reproduces the committed snapshot (catches transformers/config drift).
  describe "Descriptor snapshot" $ do
    it "matches descriptors/qwen38-27b.json when INFER_MODEL_DIR is set" $ do
      modelDir <- lookupEnv "INFER_MODEL_DIR"
      case modelDir of
        Nothing -> hPutStrLn stderr "skipped (INFER_MODEL_DIR not set)"
        Just dir -> do
          snapshot <- BS.readFile "descriptors/qwen38-27b.json"
          adapted <- qwen35DescriptorFromDir dir
          case adapted of
            Left err -> expectationFailure ("adapter failed: " ++ err)
            Right desc -> case decodeDescriptor snapshot of
              Left err -> expectationFailure ("snapshot does not parse: " ++ err)
              Right want -> do
                unless (desc == want) $ do
                  hPutStrLn stderr "snapshot differs from the adapter output:"
                  hPutStrLn stderr ("  adapter : " ++ show desc)
                  hPutStrLn stderr ("  snapshot: " ++ show want)
                desc `shouldBe` want
