# gen_build_info.cmake - emit build_info.h from the actual build inputs.
#
# Run at *build* time by CMake (cmake -P) so the header cannot go stale relative
# to the artefacts it describes, and so the manifest's build provenance is read
# from what the build really did rather than from a label someone typed:
#
#   * the git revision comes from the working tree;
#   * the Triton/FLA versions come from the file the AOT generator wrote after
#     asserting them;
#   * the artefacts are hashed from the generated sources themselves;
#   * the toolkit, arch lists and compile flags come from the CMake
#     configuration that compiled them.
#
# List-valued arguments (arch lists, compile flags) arrive '|'-joined because a
# semicolon or a space in a -D value would be split by the command line.
#
# Required variables:
#   GENERATED       directory holding the generated kernels + aot_versions.txt
#   OUTPUT          header to write
#   SOURCE_DIR      repository root (for git)
#   ENGINE_VERSION  package version
#   CUDA_TOOLKIT    toolkit version CMake found
#   CUDA_ARCHS_ARG  CMAKE_CUDA_ARCHITECTURES, '|'-joined
#   TRITON_ARCHS_ARG  the AOT targets, '|'-joined
#   FLASHINFER_HEADER path to the FlashInfer header the engine compiles against
#   NVCC_FLAGS_ARG  CUDA compile flags, '|'-joined

function(sha256_of_file path out_var)
  if(EXISTS "${path}")
    file(SHA256 "${path}" value)
  else()
    set(value "")
  endif()
  set(${out_var} "${value}" PARENT_SCOPE)
endfunction()

sha256_of_file("${FLASHINFER_HEADER}" flashinfer_sha)
sha256_of_file("${GENERATED}/aot_kernels.cpp" aot_sha)
sha256_of_file("${GENERATED}/causal_conv1d_update.cuh" conv_sha)
# One digest for the generated-kernel set, so "the kernels changed" is a single
# field a comparison can refuse.
string(SHA256 generated_sha "${aot_sha}${conv_sha}")

set(triton_version "")
set(fla_version "")
if(EXISTS "${GENERATED}/aot_versions.txt")
  file(STRINGS "${GENERATED}/aot_versions.txt" version_lines)
  foreach(line IN LISTS version_lines)
    if(line MATCHES "^triton=(.+)$")
      set(triton_version "${CMAKE_MATCH_1}")
    elseif(line MATCHES "^fla=(.+)$")
      set(fla_version "${CMAKE_MATCH_1}")
    endif()
  endforeach()
endif()

set(git_commit "")
find_package(Git QUIET)
if(GIT_FOUND)
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse HEAD
                  OUTPUT_VARIABLE git_commit OUTPUT_STRIP_TRAILING_WHITESPACE
                  ERROR_QUIET RESULT_VARIABLE git_status)
  if(NOT git_status EQUAL 0)
    set(git_commit "")
  endif()
endif()

string(REPLACE "|" ";" cuda_archs "${CUDA_ARCHS_ARG}")
string(REPLACE "|" ";" triton_archs "${TRITON_ARCHS_ARG}")
string(REPLACE "|" " " nvcc_flags "${NVCC_FLAGS_ARG}")
string(SHA256 nvcc_flags_sha "${nvcc_flags}")

set(content "/* Generated by csrc/gen_build_info.cmake at build time. Do not edit. */
#pragma once

#define ENGINE_BUILD_ENGINE_VERSION \"${ENGINE_VERSION}\"
#define ENGINE_BUILD_GIT_COMMIT \"${git_commit}\"
#define ENGINE_BUILD_CUDA_TOOLKIT \"${CUDA_TOOLKIT}\"
#define ENGINE_BUILD_CUDA_ARCHS \"${cuda_archs}\"
#define ENGINE_BUILD_TRITON_ARCHS \"${triton_archs}\"
#define ENGINE_BUILD_TRITON_VERSION \"${triton_version}\"
#define ENGINE_BUILD_FLA_VERSION \"${fla_version}\"
#define ENGINE_BUILD_FLASHINFER_HEADER_SHA256 \"${flashinfer_sha}\"
#define ENGINE_BUILD_NVCC_FLAGS_SHA256 \"${nvcc_flags_sha}\"
#define ENGINE_BUILD_GENERATED_KERNELS_SHA256 \"${generated_sha}\"
")

file(WRITE "${OUTPUT}.tmp" "${content}")
# Atomic-ish: only replace the header once it is complete, so a failed generator
# run cannot leave a half-written header for the compiler to read.
file(RENAME "${OUTPUT}.tmp" "${OUTPUT}")
